### ISSUE TITLE
bug with "niveau"

### ISSUE THREAD

**Issue by WarnDa** [Zrips/TradeMeAddon#60] opened 2021-07-29 01:37 UTC
If you put **niveau** word in a button in the gui menu (in the lore) then the button won't work anymore.
"iveau" "nveau" "niveu" work, but "niveau" doesn't ???

It's very strange

For example If I put 

    ToggleButton:
      Name: '&7Testbugged'
      Lore:
      - '&7Niveau'

Then the button won't work anymore

On latest plugin version (6.1.0.0), latest cmi release and paper 1.16.5

**Comment by Zrips** [comment] 2021-08-02 11:13
Cant reproduce this issue and we are not really filtering text like that so there isint any reason why it would not work. Its ether some miss format (which doesn't seam to be the case) or another plugin interferes with this specific word for some reason. 
Closing for now.

**Closed as completed by Zrips** 2021-08-02 11:13 UTC
